Repository GDSC-PKNU-21-22/AlgoAlgoAlgo, pull requests merged in 2022-02, with the labels that each got.

#7 3주차 문제풀이
  lv1/0130_문자열_내림차순으로_배치하기.py
  lv1/0130_문자열_다루기_기본.py
  lv1/0130_서울에서_김서방_찾기.py
  lv1/0130_소수찾기.py
Labels: Level1, Python

#14 3주차 추가풀이
  lv1/0130_가운데_글자_가져오기.py
  lv1/0130_같은_숫자는_싫어.py
  lv1/0130_나누어_떨어지는_숫자_배열.py
  lv1/0130_두_정수_사이의_합.py
  lv1/0130_문자열_내_p와y.py
  lv1/0130_문자열_내_마음대로_정렬하기.py
Labels: Level1, Python

#15 3주차 추가풀이 - 레벨1 카카오문제
  lv1/0130_1차_다트게임.py
  lv1/0130_비밀지도.py
Labels: Level1, Python

#16 3주차 추가풀이 - 레벨2문제
  lv2/0130_JadenCase_문자열_만들기.py
  lv2/0130_N개의_최소공배수.py
  lv2/0130_땅따먹기.py
  lv2/0130_숫자의_표현.py
  lv2/0130_최댓값과_최솟값.py
  lv2/0130_최솟값_만들기.py
  lv2/0130_피보나치_수.py
  lv2/0130_행렬의_곱셈.py
Labels: Level2, Python

#17 3주차 추가문제 - 레벨2 카카오
  lv2/kakao/0130_양궁대회.py
  lv2/kakao/0130_주차_요금_계산.py
Labels: Level2, Python

#20 4주차 문제풀이
  lv1/week04/2016.py
  lv1/week04/나머지가_1이_되는_수_찾기.py
  lv1/week04/부족한_금액_계산하기.py
  lv1/week04/최소직사각형.py
Labels: Level1, Python

#25 4주차 추가풀이
  lv2/kakao/k진수에서_소수_구하기.py
  lv2/kakao/n진수_게임.py
Labels: Level2, Python

#28 5주차 문제풀이
  lv1/week05/_3진법_뒤집기.py
  lv1/week05/두_개_뽑아서_더하기.py
  lv1/week05/약수의 개수와 덧셈.py
  lv1/week05/예산.py
Labels: Level1, Python

#32 5주차 추가풀이
  lv2/kakao/week05/_3차_파일명_정렬.py
  lv2/kakao/week05/다음_큰_숫자.py
  lv2/week05/올바른_괄호.py
Labels: Level2, Python

#41 6주차 문제풀이
  6주차/220225_L1_[1차]다트게임.cpp
  6주차/220225_L1_[1차]비밀지도.cpp
  6주차/220225_L1_가운데글자가져오기.cpp
Labels: Level1, C++
